package com.tcgpocket.energy;

/**
 * The energy types, which double as Pokemon types.
 *
 * <p>{@link #COLORLESS} is never generated by an Energy Zone and never appears
 * as a Pokemon's type. It exists only inside an attack cost, where it matches
 * any leftover energy regardless of type.
 */
public enum Type {
    GRASS,
    FIRE,
    WATER,
    LIGHTNING,
    PSYCHIC,
    FIGHTING,
    DARKNESS,
    METAL,
    DRAGON,
    COLORLESS;

    /** Whether this type can be generated by an Energy Zone and attached to a Pokemon. */
    public boolean isGeneratable() {
        return this != COLORLESS;
    }
}
