@startuml
skinparam linetype ortho

class Battle {
    - id: int
    - turn: int
    - attacker: Side
    - defender: Side
    - previousHeads: int
    
    + switchSides(): void
    + runTriggers(): void
}

class Side {
    - active: IPlayableCard
    - bench: List<? extends IPlayableCard>
    - hand: List<ICard>
    - deck: List<ICard>
    - discardPile: List<ICard>
    - points: int
    - numKnockedOut: int
    
    + shuffleDeck(): void
    + switchActive(): void
    + placeOnBench(): void
    + placeOnActive(): void
    + drawCard(): void
    + discardCard(): void
}

Battle -|> Side

@enduml