@startuml
skinparam linetype ortho

interface IAction {
    + execute(Battle): void
}

class Action implements IAction {
    - name: String
    - description: String
    - attempt: IAttempt
}

class TrainerAction implements IAction {
    - description: String
    - attempt: IAttempt
}

class WithPrecondition implements IAction {
    - condition: ICondition<Battle>
    - action: IAction
}

class MultiAttempt implements IAction {
    - attempts: List<IAttempt>
}

class ChoiceAction implements IAction {
    - choices: List<IAction>
}

@enduml