@startuml

interface IAttempt {
    + execute(Battle): void
}

/'Possible to completely cutout IAttempt and move List<Effect> into IAction? '/

class Attempt implements IAttempt {
    - effects: List<IEffect>
}


@enduml