@startuml

interface ICard {
    - name: String
    - description: String
    - id: String
    - actions: List<IAction>
}

interface IPlayableCard extends ICard {
    - hp: int
    - tool: Optional<ToolCard>
}

interface TrainerCard extends ICard {
}

/' Fossil cards, their IAction will be to discard itself '/
class PlayableItemCard implements IPlayableCard, TrainerCard {
}

class ItemCard implements TrainerCard {
}

class SupporterCard implements TrainerCard {
}

class ToolCard implements TrainerCard {
    - triggers: List<ITrigger>
}

class StadiumCard implements TrainerCard {
    - triggers: List<ITrigger>
}

/' Will also need tags to track whether the card is a mega, EX, etc. '/
class PokemonCard implements ICard, IPlayableCard {
    - stage: int
    - type: Type
    - ability: Optional<IAbility>
    - retreatCost: int
    - weakness: Optional<Type>
    - weaknessDamage: Optional<Integer>
}

@enduml