@startuml
skinparam linetype ortho

interface ITarget {
    + resolve(Battle): IPlayableCard
}

class AttackerActive implements ITarget {}
class OpponentActive implements ITarget {}
class AttackerBenchRandom implements ITarget {}
class OpponentBenchRandom implements ITarget {}
class AttackerRandom implements ITarget {}
class OpponentRandom implements ITarget {}
class AttackerBenchSpecific implements ITarget {
    - benchIndex: int
}
class OpponentBenchSpecific implements ITarget {
    - benchIndex: int
}

/' Formatting, these are not actually linked '/ 
AttackerBenchRandom -[hidden]- IMultiTarget
AttackerBenchSpecific -[hidden]- ISideTarget

interface IMultiTarget {
    + resolve(Battle): List<IPlayableCard>
}

class AttackerBench implements IMultiTarget {}
class OpponentBench implements IMultiTarget {}
class AttackerAll implements IMultiTarget {}
class OpponentAll implements IMultiTarget {}

interface ISideTarget {
    + resolve(Battle): Side
}

class AttackerSide implements ISideTarget {}
class OpponentSide implements ISideTarget {}

@enduml